#!/bin/bash

clear
echo -e "\033[1;31mAtalhos \033[1;36m Todos as opções disponíveis no Script podem ser acessados por um número que a corresponde, no caso o número de origem seguida o número da opção no sub Menu.\033[0m" 
echo -e "\033[1;31mExemplo:\033[0m"
echo -e "\033[1;36m Supondo que queira alterar o Hostname do servidor, o caminho lógico seria \033[1;31madm > 2 > 12\033[1;36m, onde o \033[1;31m2 \033[1;36mé a opção de \033[1;35mConfiguração e informações sobre o sistema desse servidor.\033[1;36m no menu principal e a em seguida a opção\033[1;31m 12\033[1;36m Que é o número da opção para trocar o Hostname, então para trocar o Hostname o comando direto seria \033[1;31m12.\033[0m"
echo " "
echo -e "\033[1;36m Para ter acesso a todas as opções mande o comando \033[1;31madm.\033[0m"