#!/bin/bash

clear
echo -e "\033[1;36m CONFVPS é o gerenciador feito por Glemysson, script lembra um pouco o VPSMANAGER do MITO PH. \033[1;31mPara prosseguir com a instalação aperte ENTER, para cancelar CTRL + C.\033[0m"
read  #enter
echo -e "\033[1;36m           Iniciando instalação do CONFVPS.\033[0m"
sleep 2
rm install
rm install.1
clear
apt-get update -y
apt-get install wget sudo -y
wget https://raw.githubusercontent.com/glemysson-Hacker/GlEmYsSoN/master/installer.sh
chmod +x installer.sh
bash installer.sh
sleep 3
clear
2