#!/bin/bash

clear
echo -e "\033[1;36m Isso irá configurar totalmente o seu servidor, o squid será instalado e configurado, poderá escolher entre dois script gerenciador, VpsPack ou CONFVPS, e será instalado também o BadVPN.\033[1;31m Para continuar pressione ENTER para cancelar pressione CTRL + C.\033[0m"
read #enter
echo " "
echo -e "\033[1;37mEscolha um dos script gerenciador abaixo.\033[0m" 

echo -e "
\033[1;36m1 | VpsPack
  \033[0;37m|Instalar o VpsPack, script feito por Luiz. 
\033[1;36m2 | CONFVPS
  \033[0;37m|Instalar o CONFVS feito por Glemysson. 
\033[1;36m3 | Nenhum
  \033[0;37m|Pular essa etapa e não instalar nenhum.
\033[1;31m Devido a problemas de incompatibilidade não tem opção para instalar o PackSSH, para instalar use o comando \033[1;36m2033.\033[0m"
read -p "Opção:" opcao

case $opcao in
 1)
clear
echo -e "\033[1;36mVpsPack é um ótimo script para criar, apagar, definir limite de usuários, etc. VpsPack foi criado por Luiz. \033[0m"
sleep 3
rm install
rm install.1
apt-get update -y 
apt-get install wget sudo -y
clear
echo -e "\033[1;36m          Iniciando instalação do VpsPack.\033[0m"
sleep 3
wget https://raw.githubusercontent.com/RicKbrL/VpsPack/master/install && bash install
sleep 4
clear
2034C;;
 2) 
echo -e "\033[1;36m CONFVPS é o gerenciador feito por Glemysson.\033[0m"
rm install
rm install.1
clear
apt-get update -y
apt-get install wget sudo -y
clear
sleep 3
echo -e "\033[1;36m           Iniciando instalação do CONFVPS.\033[0m"
sleep 2
wget https://raw.githubusercontent.com/glemysson-Hacker/GlEmYsSoN/master/installer.sh
chmod +x installer.sh
bash installer.sh
sleep 4
clear
2034C;;
 3)
 2034C;;
 *)
  id > /dev/null 2> /dev/null
 esac