#!/bin/bash

if [ $(id -u) -eq 0 ]
then
 clear
else
 if echo $(id) |grep sudo > /dev/null
 then
 clear
 echo "Não é root e nem tem direitos root."
 echo "Parabéns seu usuario esta no grupo sudo."
 echo -e "Para virar root execute \033[1;31msudo su\033[0m"
 exit
 else
 clear
 echo -e "Você nao esta como usuario root, nem com seus direitos (sudo)\nPara virar root execute \033[1;31msu\033[0m e digite sua senha root"
 exit
 fi
fi

clear
echo " "
echo -e "\033[1;36m        .......:::::::Adm Script, created by Devim:::::::......\033[0m"
echo -e "\033[1;37mPara executar um comando escolha uma das opçoẽs abaixo ou pode pode mandar o nome número da opção sem uso do comando adm.\033[0m"  

echo -e "\033[1;31mPara sair precione Ctrl + C\033
 \033[1;36m1 | Hardware
  \033[0;37m|Informações sobre o hardware desse servidor.
\033[1;36m2 | Sistema
  \033[0;37m|Configuração e informações sobre o sistema desse servidor.
\033[1;36m3 | Reiniciar
  \033[0;37m|Reiniciar servidor.
\033[1;36m4| Velocidade
  \033[0;37m|Teste de velocidade, conexão (Created Luiz).
\033[1;36m5| Sobre
  \033[0;37m|Informações sobre o Adm Script.
\033[1;36m6| Desinstalar
  \033[0;37m|Desinstalar o Adm Script.\033[0m"
read -p "Opção:" opcao

case $opcao in
 1)
  1;;
 2) 
  2;;
 3)
  3;;
 4)
  4;;
 5)
  5;;
 6)
  6;;
  *)
  id > /dev/null 2> /dev/null
esac