#!/bin/bash

cd

if [ $(id -u) -eq 0 ]
then
        clear
else
        if echo $(id) |grep sudo > /dev/null
        then
        clear
        echo "Voce não é root"
        echo "Seu usuario esta no grupo sudo"
        echo -e "Para virar root e fazer a instalação execute \033[1;31msudo su\033[0m"
        exit
        else
        clear
        echo -e "Vc pecisa esta como root para poder fazer a instalção, Para virar root execute \033[1;31msu\033[0m e digite sua senha root"
        exit
        fi
fi

if [ -f /bin/adm ]
  then
  echo -e "\033[1;31mERRO!  \033[1;36mAdmScript já está instalado.\033[0m"
  echo " "
  echo -n -e "\033[1;35mPara desinstalar o \033[1;36mAdmScript \033[1;35minstalado atualmente pressione \033[1;31mENTER.\033[0m"
  read #enter
   clear
   echo -e "\033[1;31mDesinstalando...\033[0m"
   rm /bin/adm
   rm /bin/1
   rm /bin/2
   rm /bin/3
   rm /bin/4
   rm /bin/101
   rm /bin/102
   rm /bin/103
   rm /bin/104
   rm /bin/201
   rm /bin/202
   rm /bin/203
   rm /bin/2031
   rm /bin/2032
   rm /bin/2033
   rm /bin/204
   rm /bin/2041
   rm /bin/2042
   rm /bin/2043
   rm /bin/205
   rm /bin/206
   rm /bin/207
   rm /bin/207.py
   rm /bin/208
   rm /bin/209
   rm /bin/210
   rm /bin/211
   rm /bin/212
   rm /bin/213
   rm /bin/214
   rm /bin/217
   rm /bin/218
   rm /bin/2034C
   sleep 5
   rm /bin/5
   clear
   echo -e "\033[1;31m               Desinstalação concluída.\033[0m"
   echo -e "\033[1;36m Preparando para reinstalar o AdmScript.\033[0m"
   sleep 5
   wget https://raw.githubusercontent.com/Devimla/AdmScript/master/install && bash install
  true
  else
  echo -e "\033[46mTermos para instalação do AdmScript, só instale se os aceitar.\033[0m"
  echo " "
  echo -e "\033[1;31m1 >> \033[1;36mEsse script é livre e sem fins lucrativos, e por essa razão a venda é proibida.\033[0m"
  echo " "
  echo -e "\033[1;31m2 >> \033[1;36mEsse script  não é um gerenciador que cria, deleta, define limite, data de expiração, etc, ele é apenas um utilitário com opções para lhe ajudar no dia a dia como trocar senha do usuario atual, reiniciar e etc.\033[0m"
  echo " "
  echo -e "\033[1;31m3 >> \033[1;36mScript feito com base no VpsPack de Rick, e também com scripts de BadGuy. Todos os direitos a eles reservados.\033[0m"
  echo " "
  echo -e "\033[1;31m4 >> \033[1;36mO autor desse script  não se responsabiliza por uso inadequado do script, ele está em português e com cores para lhe guiar.\033[0m"
  echo " "
  echo -e "\033[1;31m5 >> \033[1;36mScript foi feito e testado em sistemas Ubuntu 14, 15 e 16, suporte e garantia de funcionamento em outras versões não garantida.\033[0m
  echo " "
  echo -e "\033[1;31m6 >> \033[1;36mSe realizar modificações deixará os créditos ao criador Mr.Devim.\033[0m"
  echo " "
  echo -e "\033[1;31m7 >> \033[1;36mSe responsabilizará por qualquer operação(ões) e alteração(ões) que você efetuar com esse script.\033[0m"
  echo " "
    echo -e "\033[1;36mCaso concorde com os termos descritos acima pressione  ENTER, caso não tenha concordado \033[1;31mCTRL + C.\033[0m"
    read  #enter
    clear
    echo -e "\033[1;36m Iniciando instalação, aguarde.\033[0m"
    sleep 3
    if yum -y update
    then
    yum -y update
    yum -y install git
    git clone https://github.com/Devimla/AdmScript.git
    clear
    cd AdmScript
    rm -rf README.md
    rm -rf install
    for arqs in `ls`
    do
    rm /bin/$arqs 2>/dev/null
    mv $arqs /bin
    chmod +x /bin/$arqs
    done
    echo -e "\033[1;36mConcluido, execute o comando \033[1;31madm\033[1;36m como usuário root \033[0m"
    else
    apt-get update
    apt-get install -y git
    git clone https://github.com/Devimla/AdmScript.git
    clear
    cd AdmScript
    rm -rf README.md
    rm -rf install
    for arqs in `ls`
    do
    rm /bin/$arqs 2>/dev/null
    mv $arqs /bin
    chmod +x /bin/$arqs
    done
    echo -e "\033[1;36mConcluido, execute o comando \033[1;31madm\033[1;36m como usuário root \033[0m"
    fi
    cd
    rm -rf install 2> /dev/null
    rm -rf AdmScript 2> /dev/null
fi