#!/bin/bash

cd

if [ $(id -u) -eq 0 ]
then
        clear
else
        if echo $(id) |grep sudo > /dev/null
        then
        clear
        echo "Desculpem-me, mas você não é root"
        echo "Seu usuario esta no grupo sudo"
        echo -e "Para virar root e fazer a instalação execute \033[1;31msudo su\033[0m"
        exit
        else
        clear
        echo -e "\033[1;36mVocê não está como root, e nem tem os privilégios, para virar root mande o comando \033[1;32msu \033[1;36me em seguida a senha do usuário root\033[0m"
        exit
        fi
fi

echo -e "\033[1;36mSe prosseguir será instalado o Adm Script, script baseado no VpsPack.\033[1;31m Para prosseguir aperte ENTER, para cancelar CTRL + C.\033[0m"
read  #enter
clear
echo -e "\033[1;36m Iniciando instalação, aguarde.\033[0m"
sleep 6
if yum -y update
then
apt-get update
apt-get install wget sudo
yum -y update
yum -y install git
git clone https://github.com/Devimla/AdmScript.git
clear
cd AdmScript
rm -rf README.md
rm -rf install
for arqs in `ls`
do
rm /bin/$arqs 2>/dev/null
mv $arqs /bin
chmod +x /bin/$arqs
done
clear
sleep 4
echo -e "\033[1;36mInstalação concluída com êxito, mande o comando adm para ter as opções.Só funciona com usuário root ou usuário com privilégios root.\033[0m"
else
apt-get install wget sudo
apt-get update
apt-get install -y git
git clone https://github.com/Devimla/AdmScript.git
clear
cd AdmScript
rm -rf README.md
rm -rf install
for arqs in `ls`
do
rm /bin/$arqs 2>/dev/null
mv $arqs /bin
chmod +x /bin/$arqs
done
echo -e "\033[1;36mInstalação concluída com êxito, mande o comando adm para ter as opções.Só funciona com usuário root ou usuário com privilégios root.\033[0m"
fi
cd
rm -rf install 2> /dev/null
rm -rf AdmScript 2> /dev/null
rm install
